language: python
python:
  - "3.5"
script: true
install:
  - "pip install mkdocs"
  - "pip install mkdocs-cinder"
  - "pip install markdown-include"
  - "sudo apt-get install xfonts-encodings"
  - "wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz"
  - "tar -xvf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz"
  - "sudo mv wkhtmltox/bin/wkhtmltopdf /usr/bin/wkhtmltopdf"
  - "wkhtmltopdf --version"
after_success:
  - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./.deploy.sh ; fi
env:
  global:
    - SITE_URL: https://o2r.info/architecture
    - GH_USER_NAME: "Opening Reproducible Research"
    - GH_USER_EMAIL: openingrr@uni-muenster.de
    - GH_REF: github.com/o2r-project/architecture
    - secure: "BmRwCfi2mWj1zPUk3NTVxONitLmLNGUGyKLTB26ZdFi2RNWYvNZb1TLKb6uuBmQjRvAIfbcpkwW+RhXhcgbphzBQWzczNXRk43IKyErGFNfCzx9mQ0FeWfODiHsU6eROBKcPNSeFn8irMJQnxuxgy2DpE4rY0FOkFs5KeiCe7zwsGy0/wq23vJkgGkET+8Rt2w6diEJvPdgRw8FPSJVd/+bPnIKQlEf+v+AgItboYNMCkAuLeCpHwA01fbLsF16yGKmFTgjptswaQhdMndYEeEdd/38Uu1Nr2pP00sgRQmWG7Tqt0tBkw0AuIOhYmf1b4SWEDqO10UGAoKHnhgRmVanh2hspIbeTobwl0burSupQ+SPcqddZJaD0VdrwLNVIYQojSooNLhrjQP6l98CQ/FqgeyGQEKODQR66ONu/OvAChdPjx5mT/ghoJjpDNGA5x5+/nrUMtUwZ5NOhIKZY79gtzu86LtWDoqRmp60AdZvsHgBHMf71gO8C/fGrWk2b0/6GVRj8F7dKQ20OENOHg3EsXmOVEEN2tJ3DIuzeevP/4fHg5PAFrFZ5qGUZ9dIZOTt4HCsqST6+jjp4HrptVwG093CSXTx4UV1tyTgdg3xjZZmOdj6bpQQyZDGtGTCKp1esxVvLcFS0StvDGTXVMYhVrMR8Egn0oWf0PYAOpfM="