language: python
python:
  - "3.5"
script: true
install:
  - "pip install mkdocs"
  - "pip install mkdocs-cinder"
  - "pip install markdown-include"
after_success:
  - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./.deploy.sh ; fi
env:
  global:
    - SITE_URL: https://o2r.info/architecture
    - GH_USER_NAME: "Opening Reproducible Research"
    - GH_USER_EMAIL: openingrr@uni-muenster.de
    - GH_REF: github.com/o2r-project/architecture
    - secure: "C0o5wzp2SX3RnrVILWbi+aAKFuz2Md4Kw1qoXGs5LG+Ie5CPWtrRjR6Zd+F3Xxeod36INV4BK+iEC/CD3M8gitsDnlogloVEQVCFuUIciurK14F5cpJ2tlFOZjRYyG4Oq4pX+ItbEfJ5M7ydiuZKz9rj/og2QkSG39RcV3IbZ/j4zdM6K92F0LEhZTTsALo2L5NQMUDBX4VxAY/8nGG8XdBxIo9qhAseLcgydB2lOvr1cn957Pya1zdrvqVuYo/KJFhA/H18wfyYanJ6zWMXQu3XddPdOG8ypTsWLUKxvyxpDP4Ut42G2DmF60YNJjEhYeqNuFlheJOHAdRBIEnctOEOlxVrdnkfUNR9ZSrDjqx/NwKrbf9g1P41Jef1+KNODxfp8o44GZLToNZUuQjmcwB+w8YWOc1V8GTwCgNSlB6xk0BlUji25i1Cl1cdz/s+peTqQdkaFrNq5p4Nezy2el2f1NLwQm0BKOOY1DgFzwyJLAYbq8xCI4FyYfMAJfCLW43g9IesAAe5YyXXTdnsYRZxPr9XIKVpcfDMJmXANnvahD6XAzJl2u5EszYhI1DJ9NL4wsDm8PEdAk44wku4YehNAlyUKlIo6LmFN6Za53X7JTI0/buwuKraMm10Ganqi4d6JyC20Ve9vxEK/1b2Ixqz5a3K43AQNw/Y/NmOG3U="
