site_name: Architecture for o2r
site_description: Software architecture for Opening Reproducible Research
site_author: "Daniel Nüst, Matthias Schutzeichel, Jörg Lorenz"
pages:
  - Architecture: index.md
  - User scenarios: user-scenarios.md
  - Glossary: glossary.md
  - Metadata: metadata.md
theme: readthedocs
site_author: o2r project
site_dir: site
theme_dir: custom_theme
extra_css: [arc42.css]
repo_url: https://github.com/o2r-project/architecture
repo_name: GitHub
edit_uri: tree/master/docs/
markdown_extensions:
  - markdown_include.include
  - markdown.extensions.admonition
  - def_list