site_name: o2r Architecture
site_description: Opening Reproducible Research System Architecture
site_author: "Daniel Nüst, Matthias Schutzeichel, Jörg Lorenz"
nav:
  - Architecture: index.md
  - 'User scenarios': user-scenarios.md
  - Glossary: glossary.md
  - Metadata: metadata.md
  - Zenodo integration: zenodo.md
theme:
    name: readthedocs
    custom_dir: custom_theme
site_author: o2r project
site_dir: site
site_url: https://o2r.info/architecture/ 
extra_css: [arc42.css]
repo_url: https://github.com/o2r-project/architecture
repo_name: GitHub
edit_uri: tree/master/docs/
markdown_extensions:
  - markdown_include.include
  - markdown.extensions.admonition
  - def_list
  - toc(permalink=true)
